import {useState} from 'react';
import {Building2,Search,Users,Mail,CheckCircle2,Megaphone,Bot,Send,Clock} from 'lucide-react';
import {companyFromCommand} from './companyCommand';
export default function CompanyConnectWorkflow({drive,searched,matches,onSearch,searching}){
 const [command,setCommand]=useState(''),[error,setError]=useState(''),[expanded,setExpanded]=useState(false);
 const invitations=drive?.invitedAlumni||[];
 const steps=[['Drive created',Building2,!!drive],['Company searched',Search,searched],['Alumni found',Users,searched&&matches.length>0],['Emails sent',Mail,invitations.some(i=>i.delivery?.email==='sent')],['Mentor accepted',CheckCircle2,invitations.some(i=>i.status==='ACCEPTED')],['Students notified',Megaphone,!!drive?.broadcastAt]];
 const activity=drive?[{id:'created',at:drive.createdAt,text:`${drive.companyName} drive created`},...invitations.flatMap(i=>[{id:i.id,at:i.sentAt,text:`Invitation saved for ${i.name} · email ${i.delivery?.email||'pending'}`},...(i.respondedAt?[{id:`response-${i.id}`,at:i.respondedAt,text:`${i.name}: ${i.status.toLowerCase()}`}]:[])]),...(drive.broadcastAt?[{id:'broadcast',at:drive.broadcastAt,text:'Eligible students notified'}]:[])].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,4):[];
 async function submit(e){e.preventDefault();const company=companyFromCommand(command);if(!company){setError('Try “Find alumni at COMPANY” or enter a company name.');return;}setError('');await onSearch(company);setExpanded(false);}
 return <section className="cc-workflow"><button className="cc-workflow-toggle" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>Search assistant &amp; workflow {expanded?'−':'+'}</button><div className={`cc-workflow-body ${expanded?'expanded':' '}`}><ol className="cc-progress" aria-label="Placement workflow">{steps.map(([label,Icon,done])=><li key={label} className={done?'done':''}><span><Icon size={17}/></span><small>{label}</small></li>)}</ol><section className="cc-assistant-grid"><div className="cc-assistant"><div className="cc-assistant-title"><Bot size={24}/><div><strong>Company Connect Assistant</strong><small>Company search · review recipients before sending</small></div></div><form onSubmit={submit}><label htmlFor="cc-command">Give a search command</label><div><input id="cc-command" value={command} onChange={e=>setCommand(e.target.value)} placeholder={drive?`Find alumni at ${drive.companyName}`:'Find alumni at a company'} disabled={!drive||searching}/><button className="admin-action" disabled={!drive||searching||!command.trim()} aria-label="Run company search command"><Send size={16}/></button></div>{error&&<p role="alert">{error}</p>}</form></div><aside className="cc-activity"><strong><Clock size={15}/>Activity log</strong>{activity.length?<ul>{activity.map(a=><li key={a.id}><span>{a.text}</span><time>{new Date(a.at).toLocaleString('en-IN',{dateStyle:'short',timeStyle:'short'})}</time></li>)}</ul>:<p>Create a drive to start the placement workflow.</p>}</aside></section></div></section>;
}


